# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/play_be
    docker:
      - image: circleci/node:7.10
        environment:
          NODE_ENV: test
          PG_HOST: 127.0.0.1
          POSTGRES_DB: postgres_db
          POSTGRES_USER: postgres
          PG_PASSWD: boilerplate
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: postgres_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: boilerplate

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: install postgresql-client
          command: |
            sudo apt-get update
            sudo apt-get add postgresql-client

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: create database
          command: |
            set PGPASSWORD=boilerplate
            psql --host localhost -U postgres -d postgres_db < .circleci/play_app_test.sql

      - run:
          name: Set Up DB
          command: knex migrate:latest
      # run tests!

      - run: npm test


    # steps:
    #   - run:
    #       name: Set up DB
    #       command: |
    #         bundle exec rake db:create db:schema:load --trace
    #         bundle exec rake db:migrate
    #     environment:
    #       DATABASE_URL: "postgres://ubuntu@localhost:5432/db_name"
